# Site
name: 'Big Data cơ bản'
description: 'Big data cơ bản tutorial'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'Big Data cơ bản'
email: 'hamintrip@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    hamin:
      name:           HaMin
      site:           https://bigdatacoban.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am hamin, the author of Big Data cơ bản"
      email:          hamintrip@gmail.com
      twitter:        https://twitter.com/hamintrip
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: hamin
      avatar: /assets/images/avatar.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
theme: jekyll-theme-minimal
